$xlsx_path = "C:\Users\AXL\.gemini\antigravity\scratch\Ammar Perfumería\Base_Datos_Perfumes.xlsx"
$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false

$workbook = $excel.Workbooks.Open($xlsx_path)
$worksheet = $workbook.Sheets.Item(1)
$lastRow = $worksheet.Cells.SpecialCells(11).Row

for ($row = 2; $row -le $lastRow; $row++) {
    $ref = $worksheet.Cells.Item($row, 2).Value2
    if (-not $ref) { continue }
    
    $tips = ""
    
    switch -Regex ($ref) {
        "(?i)^9am Dive$" { $tips = "Fragancia fresca, acuática y ultra versátil. Excelente para el día a día, clima cálido y oficina. Comparte un ADN limpio y magnético similar al icónico Bleu de Chanel y YSL Y, garantizando cumplidos por su vibra de hombre recién duchado y elegante." }
        "(?i)^9pm$" { $tips = "El rey absoluto de la fiesta y la noche. Es un clon directo y mejorado de Ultra Male de Jean Paul Gaultier. Destaca por su explosión dulce de manzana, vainilla y canela que proyecta masculinidad seductora. Ideal para discotecas, citas y climas fríos. Proyección bestial." }
        "(?i)^9pm Rebel$" { $tips = "Una versión moderna y rebelde del 9pm clásico. Incorpora una nota vibrante y tropical de piña dulce que lo hace más afrutado, divertido y versátil, manteniendo el fondo acaramelado. Perfecto para quienes buscan destacar con un aroma dulce pero fresco." }
        "(?i)^Cloud$" { $tips = "Uno de los perfumes más virales y deseados. Ofrece un dulzor cremoso y adictivo gracias a la crema batida, el coco y el praliné. Es famoso por ser una de las mejores y más acogedoras alternativas al carísimo Baccarat Rouge 540. Tierno, femenino y duradero." }
        "(?i)^Cloud 2\.0 Intense$" { $tips = "La versión superior y más profunda de Cloud. Refuerza las maderas rubias y el ambroxan para darle mayor fijación, duración y estela. Pierde un poco de la nota láctea para volverse un perfume más sofisticado y maduro, ideal para usar como firma personal." }
        "(?i)^Cloud Pink$" { $tips = "La variante más frutal, jugosa y tropical de la línea Cloud. Introduce la pitahaya (fruta del dragón) y frutos rojos, aportando un toque brillante y coqueto sin perder el ADN cremoso y avainillado original. Perfecto para primavera, verano y espíritus jóvenes." }
        "(?i)^Mod Blush$" { $tips = "Una fragancia moderna, vibrante y muy femenina. Abre con una explosión chispeante de maracuyá y frambuesa, asentándose en un corazón de rosa y un fondo limpio de maderas. Transmite energía, frescura y sofisticación. Ideal para el uso diario y oficina." }
        "(?i)^R\.?E\.?M(_Alt)?$" { $tips = "Un perfume gourmand inusual, relajante y sumamente original. Combina una lavanda limpia con un toque salado, caramelo y malvavisco dulce. Crea una burbuja de aroma reconfortante y onírico. Perfecto para climas fríos, noches tranquilas o uso en espacios cerrados." }
        "(?i)^Thank U Next$" { $tips = "Una fragancia juvenil, coqueta y veraniega por excelencia. Su ADN está dominado por notas de coco dulce y repostería (azúcar de macarrón). Transmite una vibra de playa, bronceador de lujo y postres dulces. Ideal para mujeres que aman los aromas gourmand tropicales." }
        "(?i)^Club de Nuit Intense$" { $tips = "El clon más famoso y exitoso de la historia de la perfumería (clon exacto de Creed Aventus). Ofrece una salida cítrica punzante de limón y piña, que evoluciona hacia un secado masculino, ahumado y amaderado. Rendimiento brutal y máquina absoluta de cumplidos." }
        "(?i)^Club de Nuit Woman$" { $tips = "Una alternativa precisa, elegante y de altísimo rendimiento al legendario Coco Mademoiselle de Chanel. Combina cítricos chispeantes con un corazón de rosa y jazmín, sobre una base madura de pachulí. Transmite clase, profesionalismo y feminidad empoderada." }
        "(?i)^Club de Nuit Untold$" { $tips = "Un clon premium y de altísima calidad del lujoso Baccarat Rouge 540 Eau de Parfum. Posee ese inconfundible aroma dulce, metálico y amaderado a 'algodón de azúcar tostado' gracias a la mezcla de azafrán, jazmín y ámbar gris. Proyección y duración nucleares." }
        "(?i)^Lionheart(_Alt)?$" { $tips = "Un perfume oriental fougère imponente, maduro y muy elegante. Sus notas de lavanda y menta le dan frescura clásica, mientras la vainilla, el tabaco y la miel lo vuelven seductor y cálido. Una fragancia con presencia de líder, ideal para eventos formales o clima frío." }
        "(?i)^Odyssey Mandarin Sky$" { $tips = "Un contraste perfecto entre cítricos vibrantes y dulzor seductor. Destaca la mandarina caramelizada y el haba tonka. Es una alternativa directa al exitoso Scandal Pour Homme de Jean Paul Gaultier. Joven, juguetón y perfecto para citas o salidas nocturnas." }
        "(?i)^Odyssey Mandarin Sky Elixir$" { $tips = "La versión intensificada, más especiada y profunda de Mandarin Sky. Añade toques de cardamomo, incienso y pimienta negra que oscurecen la fragancia y le dan un misterio oriental. Mucho más formal, duradero y potente que el original." }
        "(?i)^Acqua di Gio Profondo$" { $tips = "La evolución moderna del mayor clásico de la perfumería masculina. Es una inmersión en el océano: hiper-marino, mineral, salado y muy aromático. Perfecto para el calor extremo, el gimnasio o la oficina. Proyecta una imagen pulcra, profesional y masculina." }
        "(?i)^S[iì] Passione$" { $tips = "Una fragancia roja, vibrante, femenina y muy frutal. Se aleja del misterio del 'Sì' clásico para ofrecer una mezcla jugosa de pera, grosella, piña y rosa. Es un aroma alegre, romántico y moderno, ideal para citas casuales, primavera y uso diario." }
        "(?i)^King$" { $tips = "Una explosión frutal arrolladora. Es un clon potente con el ADN dulce y almizclado del famosísimo Erba Pura de Xerjoff. Ofrece cítricos brillantes que se funden en una base de vainilla y ámbar. Su duración y proyección son de nivel 'bestia'. No pasarás desapercibido." }
        "(?i)^Niche Femme$" { $tips = "Un perfil aromático oriental-floral que huele a exclusividad y lujo nicho. Con una alta concentración de aceites, destaca la rosa turca entrelazada con incienso y sándalo. Para mujeres seguras de sí mismas, ideal para eventos formales, galas o la noche." }
        "(?i)^212 VIP Black$" { $tips = "El aroma definitivo de la vida nocturna urbana y moderna. Abre con una nota alcohólica y herbal de absenta y anís, secando en una vainilla oscura y cuero magnético. Joven, fiestero, dulce pero misterioso. Una apuesta segura para el antro y las salidas de fin de semana." }
        "(?i)^Very Good Girl$" { $tips = "Un giro tropical, jugoso y divertido del clásico Good Girl. Cambia el café y cacao por un lichi vibrante y una grosella roja acidita, manteniendo un fondo de rosa y vainilla. Femenino, coqueto, brillante y mucho más versátil para el día y climas cálidos." }
        "(?i)^Good Girl$" { $tips = "El icónico zapato de tacón que revolucionó el mercado. Es una fragancia intensamente sensual y nocturna, que contrasta flores blancas luminosas (jazmín, nardo) con notas oscuras y gourmand de cacao, café y almendra. El perfume definitivo para seducir." }
        "(?i)^Coco Mademoiselle$" { $tips = "El estándar de oro de la elegancia femenina moderna. Una mezcla magistral de cítricos vibrantes, rosa pura y una base terrosa y madura de pachulí y vetiver. Huele a mujer exitosa, rica y profesional. Perfecto para cualquier ocasión, especialmente como firma personal." }
        "(?i)^Aventus$" { $tips = "El pionero absoluto de la perfumería masculina moderna. Una mezcla magistral de piña jugosa, manzana y grosella negra, que reposa sobre una base masculina ahumada de abedul y ámbar gris. Símbolo de estatus, éxito y masculinidad. Versátil y elegante." }
        "(?i)^Silver Mountain Water$" { $tips = "Inspirado en la frescura gélida de los Alpes suizos. Una fragancia unisex, fresca, metálica y verde, donde destaca el té verde, la grosella y el almizcle. Transmite tranquilidad, pureza y pulcritud absoluta. Ideal para el calor o para entornos de salud/oficina." }
        "(?i)^Jadore Marina$" { $tips = "Una versión fresca y radiante. Elegancia floral clásica dominada por un hermoso bouquet de flores blancas (jazmín, magnolia) con toques frutales acuáticos. Un aura de oro líquido, sofisticación y feminidad pura." }
        "(?i)^Miss Dior$" { $tips = "La esencia del romance, la coquetería y la juventud parisina. Un perfume inmensamente floral, empolvado y dulce, donde brillan la peonía, la rosa y la vainilla. Atalcado, reconfortante y elegante, es el regalo perfecto para mujeres románticas y clásicas." }
        "(?i)^Sauvage Parfum$" { $tips = "La versión más densa, oscura, madura y misteriosa del rey de los cumplidos. Rebaja la estridencia metálica del Eau de Toilette y añade resinas de incienso, sándalo cremoso y un toque de vainilla. Proyecta masculinidad, seriedad y alto nivel adquisitivo." }
        "(?i)^Sauvage$" { $tips = "Fresco, especiado, picante y salvaje. La explosión de bergamota, pimienta negra y una sobredosis de ambroxan aseguran que dejarás rastro por donde pases. Extremadamente versátil, rinde igual de bien en la oficina, en el gimnasio o en la discoteca." }
        "(?i)^Light Blue$" { $tips = "El cítrico icónico por excelencia para mujeres. Huele al verano mediterráneo: limón siciliano ácido, manzana crujiente y maderas de bambú frescas. Es la referencia absoluta para el clima cálido, el uso diario y para transmitir energía, limpieza y positividad." }
        "(?i)^Boss Bottled Parfum$" { $tips = "Una reinterpretación oscura, profunda y formal del clásico de los 90. Destacan las maderas ricas, el cuero y el incienso, dándole un peso y una seriedad perfectos para la noche, clima frío o reuniones de negocios de alto nivel. Masculinidad en botella oscura." }
        "(?i)^Boss Bottled$" { $tips = "El clásico versátil y atemporal que nunca falla. El aroma por excelencia para la oficina, conocido por su inconfundible y reconfortante mezcla de manzana horneada, canela y vainilla sobre un fondo amaderado. Huele a hombre accesible, limpio y confiable." }
        "(?i)^Il Femme$" { $tips = "Perfumería de lujo (nicho colombiano). Posee un perfil oriental opulento de altísima calidad y concentración. Destaca por una vainilla polvorienta, maracuyá y maderas especiadas. Tiene una proyección y estela enormes. Para quienes buscan oler exclusivo, rico y diferente." }
        "(?i)^Il Roso$" { $tips = "El protagonismo absoluto de una rosa roja aterciopelada y misteriosa, combinada con ruibarbo jugoso, maderas ahumadas, incienso y ámbar. Una fragancia floral-oriental intensa, lujosa y seductora, perfecta para destacar con elegancia en eventos nocturnos." }
        "(?i)^Oud For Greatness(_Alt)?$" { $tips = "Perfumería nicho de altísimo impacto y lujo. Oscuro, misterioso y opulento. La combinación de madera de oud de alta calidad, azafrán metálico y nuez moscada crea un aura de poder y misticismo. Exige vestir bien, ideal para clima frío y eventos de gala." }
        "(?i)^Le Beau$" { $tips = "Sensualidad tropical masculina al máximo nivel. Huele a vacaciones exóticas: una madera de coco tostada, mezclada con haba tonka dulce y la frescura de la bergamota. Es un imán de cumplidos para el calor, fiestas en la playa o salidas casuales veraniegas." }
        "(?i)^Scandal$" { $tips = "Una bomba dulce, atrevida y sumamente femenina. Es una sobredosis de miel espesa, caramelo y flores blancas narcóticas (gardenia/jazmín). Extremadamente densa, nocturna y provocativa. Para mujeres que buscan llamar la atención y dejar una estela inolvidable." }
        "(?i)^L12\.?12 Blanc$" { $tips = "Frescura, deporte y pulcritud. Huele a una camiseta polo de algodón blanco recién lavada y planchada. Sus notas de toronja, nardo y cuero gamuzado lo hacen inofensivo, agradable y perfecto para después de ducharse, hacer deporte o estar relajado en casa." }
        "(?i)^Lacoste Rouge$" { $tips = "Una fragancia energética, dinámica y especiada. El contraste entre la dulzura crujiente de la manzana roja y las maderas picantes/pimienta genera un aroma activo y vibrante. Excelente opción para uso diario, universidad o ambientes casuales y juveniles." }
        "(?i)^La vie est belle$" { $tips = "El superventas absoluto de los perfumes gourmand (dulces). Una estela masiva de praliné, vainilla, grosella y flores polvorientas. Significa 'la vida es bella' y transmite exactamente eso: alegría, dulzura, optimismo y feminidad. Altísima duración y proyección." }
        "(?i)^Afeef$" { $tips = "Una joya de uso diario del mundo árabe. Combina maderas limpias con un inicio jugoso de frutas (durazno) y un fondo avainillado/praliné elegante. Es inofensivo, sofisticado y muy agradable, ideal para la oficina o el uso cotidiano sin saturar." }
        "(?i)^Asad Bourbon$" { $tips = "La novedad seductora. Un giro dulce y oriental donde destaca una potentísima vainilla bourbon, cacao y especias. Huele a postre lujoso y oscuro. Extremadamente cálido y envolvente, es una máquina para el clima frío y citas románticas cercanas." }
        "(?i)^Asad$" { $tips = "La alternativa económica definitiva al costoso Dior Sauvage Elixir. Una bofetada potente, oscura, especiada y madura, donde brilla la pimienta, el tabaco, el pachulí y un fondo de vainilla cálida. Huele a hombre maduro, seguro de sí mismo y con carácter fuerte." }
        "(?i)^Badee Al Oud Amethyst$" { $tips = "Un clon magistral del costoso Atomic Rose de Initio. La protagonista es una rosa oscura, almibarada y potente, mezclada con madera de oud y vainilla. Una fragancia mística, dulce y muy amaderada, con un rendimiento espectacular para la noche." }
        "(?i)^Badee Al Oud Honor and Glory White$" { $tips = "Un gourmand tropical completamente único en el mercado. Huele a un exótico postre de piña caramelizada o creme brulee de frutas, espolvoreado con especias (cúrcuma, canela). Dulce, lácteo, cremoso y muy alegre. Gran duración." }
        "(?i)^Badee Al Oud Oud for Glory Black$" { $tips = "El clon exacto del lujosísimo Oud for Greatness de Initio. Comparte esa misma vibra oscura, opulenta y majestuosa del oud, el azafrán y la nuez moscada. Olerás a millonario árabe por una fracción minúscula del precio. Súper elegante." }
        "(?i)^Badee Al Oud Sublime$" { $tips = "Un clon jugoso y frutal inspirado en Eden Juicy Apple de Kayali. Es una explosión fresca y dulce de manzana roja, lichi y ciruela sobre un fondo limpio de vainilla y musgo. Altamente femenino, alegre, vibrante y muy fácil de gustar." }
        "(?i)^Eclaire$" { $tips = "El clon más buscado y viral del carísimo Bianco Latte. Es una delicia puramente gourmand: extremadamente lactónico, sabe a leche condensada, caramelo derretido, miel y vainilla. Literalmente olerás a un postre delicioso recién horneado. Irresistible y acogedor." }
        "(?i)^His Confession$" { $tips = "Un lanzamiento elegante y sofisticado que se posiciona al nivel de Armani Code Absolu o YSL Tuxedo. Es un oriental amaderado impecable: especias cálidas, iris pulcro, vainilla y maderas. Transmite muchísima clase, ideal para trajes, oficina formal o citas elegantes." }
        "(?i)^Khamrah Dukhan$" { $tips = "La versión más oscura y misteriosa del best-seller Khamrah. Incorpora notas ahumadas, de incienso y tabaco sobre la base dulce original, dándole una faceta mucho más nicho, madura y profunda. Ideal para coleccionistas y amantes de los aromas complejos." }
        "(?i)^Khamrah Qahwa$" { $tips = "Un flanker sumamente exitoso. A la dulzura espectacular del original, le añade una nota prominente de café arábica recién tostado y cardamomo. Este toque amargo equilibra perfectamente el praliné y los dátiles. Cálido, adictivo y perfecto para el invierno." }
        "(?i)^Khamrah$" { $tips = "El fenómeno mundial de Lattafa, fuertemente inspirado en Angels' Share de Kilian. Es un perfume acogedor, riquísimo y festivo. Destacan los dátiles dulces, la canela, el praliné y la vainilla. Literalmente huele a un cálido pastel navideño especiado. Rendimiento brutal." }
        "(?i)^Yara Candy$" { $tips = "La adición más golosa de la familia Yara. Emula los dulces frutales y la confitería (con claras reminiscencias a Oriana de Parfums de Marly). Es una bomba de caramelo de fresa, mandarina y jarabe de vainilla. Para quienes aman oler a caramelos y gomitas dulces." }
        "(?i)^Yara Tous$" { $tips = "El Yara perfecto para el verano y las vacaciones. Su mezcla tropical de mango jugoso, coco y maracuyá evoca la sensación de un bronceador de súper lujo en una playa paradisíaca. Es vibrante, floral-frutal, alegre e invita al buen humor." }
        "(?i)^Yara$" { $tips = "El perfume árabe más viral de internet. Su aroma es frecuentemente descrito como un 'batido cremoso de fresa y vainilla'. Es extremadamente tierno, dulce, atalcado y femenino. Súper versátil, fácil de usar a diario y una apuesta 100% segura para comprar a ciegas." }
        "(?i)^Santal 33$" { $tips = "El aroma nicho de estatus y moda de Nueva York. Es un perfume amaderado muy seco, donde reina un sándalo lechoso, mezclado con cuero, papiro y toques verdes. Transmite una estética minimalista, moderna y de 'lujo silencioso'. Totalmente unisex y rompedor." }
        "(?i)^Arabians Tonka$" { $tips = "Famoso por su rendimiento nivel 'bestia'. Es una fragancia de altísima presencia: azúcar quemada, una rosa prominente y potente madera de oud. Es densa, rica, estridente y llena una habitación. Solo para quienes desean máxima atención en climas fríos o fiestas." }
        "(?i)^Starry Nights$" { $tips = "Un perfume oriental floral de gran proyección. Sorprende por una salida muy brillante de cítricos y frutas frescas, que rápidamente se oscurece con una dosis masiva de rosa, pachulí terroso y almizcle blanco. Lujoso, vibrante y muy elegante." }
        "(?i)^Toy 2 Pearl$" { $tips = "Un perfil olfativo mineral y salado muy interesante. Simula la sensación de la arena de la playa mezclada con limones y cítricos italianos vibrantes, orégano y un fondo amaderado. Es único, refrescante y aporta una brisa marina y mineral a tu día a día." }
        "(?i)^Toy 2$" { $tips = "El aroma a limpio supremo. Es la sensación embotellada de salir de una ducha de lujo o acostarse en sábanas blancas recién lavadas. Destaca una manzana verde crujiente, magnolia y almizcle blanco. Súper inofensivo, pulcro y perfecto para el día a día." }
        "(?i)^Toy Boy 2$" { $tips = "Una alternativa especiada, atrevida y poco convencional. Destaca el clavo, nuez moscada y rosa oscura. Es un perfume floral-amaderado para hombres seguros de sí mismos, con un aire misterioso y muy seductor." }
        "(?i)^Amber Rouge$" { $tips = "Un clon premium y de altísima calidad de Baccarat Rouge 540 Extrait. Captura a la perfección ese codiciado aroma a azafrán, maderas cálidas y resinas dulces (ámbar gris), añadiendo un toque ligeramente almendrado. Elegancia pura que proyecta exclusividad y riqueza." }
        "(?i)^Royal Amber$" { $tips = "Una inspiración de altísimo nivel del célebre Erba Pura de Xerjoff. Es una explosión nuclear de frutas dulces tropicales sobre una base densa de almizcle y vainilla. Es chillón, fiestero, dulce y tiene una proyección que se hace notar a metros de distancia." }
        "(?i)^Velvet Gold$" { $tips = "Una hermosa alternativa a Gentle Fluidity Gold de Maison Francis Kurkdjian. Es dulce, atalcada y ligeramente metálica. La vainilla, el caramelo y la violeta crean un aura dorada, cálida y muy lujosa. Transmite feminidad refinada, riqueza y buen gusto." }
        "(?i)^1 Million Lucky$" { $tips = "Una de las versiones más codiciadas y singulares de 1 Million. Destaca por un acorde gourmand único de avellana, miel y ciruela, mezclado con maderas frescas. Es muy dulce, juvenil, fiestero e increíblemente seductor. Una verdadera joya olfativa." }
        "(?i)^Fame( Blooming Pink)?$" { $tips = "Un ADN tropical, moderno y juguetón. Está dominado por una nota jugosa y cremosa de mango, equilibrada con jazmín puro y un fondo místico de incienso y vainilla. Es un aroma divertido, coqueto y muy 'chic' para salidas o uso diario." }
        "(?i)^Invictus$" { $tips = "El fundador del estilo 'dulce-acuático' moderno. Extremadamente popular y sintético (en el buen sentido). Una mezcla deportiva de toronja fresca, notas de mar salado, hojas de laurel y maderas dulces. Campeón en rendimiento, ideal para gimnasio y días activos." }
        "(?i)^Phantom$" { $tips = "Un choque entre tecnología, dulzor y frescura clásica. Toma la clásica lavanda aromática masculina y la envuelve en una nube densa y terrosa de limón dulce, vainilla y pachulí. Juvenil, moderno, fiestero y con una proyección inmensa." }
        "(?i)^Delina Exclusif$" { $tips = "La máxima expresión del lujo floral. Es una versión más densa, rica, dulce y empolvada de la icónica rosa turca de Delina. Se envuelve en vainilla, incienso suave y un toque de pera. Huele a una mujer moderna, rica, elegante y sumamente romántica." }
        "(?i)^Kalan$" { $tips = "Un nicho polarizante y con mucho carácter. Abre de forma sumamente punzante, terrosa y especiada (naranja sanguina y mucha pimienta negra). Seca revelando lavanda y un dulzor amaderado. Solo para hombres seguros que buscan un aroma que imponga presencia y autoridad." }
        "(?i)^Marshmallow Blush$" { $tips = "Un paraíso para los amantes de lo dulce extremo. Está centrado exclusiva y deliberadamente en el aroma suave, esponjoso y azucarado del malvavisco (marshmallow), crema de vainilla y toques sutiles de frutas y coco. Femenino, acogedor y tierno." }
        "(?i)^Rose Rush$" { $tips = "Una fragancia accesible, muy fresca y acuática centrada en la rosa. No es una rosa madura, sino juvenil, combinada con lichi y papaya, lo que le da un aire tropical, limpio y cristalino. Excelente opción económica para el día a día primaveral." }
        "(?i)^360$" { $tips = "Un clásico intocable de los años 90. Posee un perfil altamente pulcro, limpio y acuático-floral. El melón aguado, el lirio y la lavanda generan una sensación de limpieza profunda y jabonosa. Confiable, inofensivo e ideal para uso diario o de oficina." }
        "(?i)^Paradoxe Intense$" { $tips = "Una sobredosis de feminidad moderna. Toma las flores blancas luminosas (flor de azahar, neroli) del original y las intensifica con una base robusta, cálida y envolvente de musgo y ambroxan. Es dulce, denso, floral y perfecto para dejar estela en cualquier evento." }
        "(?i)^Now Women$" { $tips = "Una fantástica alternativa económica a Burberry Her. Presenta una nota predominante de fresa/maracuyá muy sintética y divertida, mezclada con aldehídos que le dan un toque atalcado y cremoso, casi como un batido de fresa limpio y almizclado. Muy jovial." }
        "(?i)^Tobacco Vanille$" { $tips = "Una obra maestra de la perfumería mundial. Recrea el aroma de un club de caballeros inglés: hoja de tabaco húmeda, especias picantes, vainilla rica y profunda, cacao y frutos secos. Es oscuro, sumamente acogedor, opulento y el rey indiscutible para invierno." }
        "(?i)^Tommy$" { $tips = "El icono absoluto de la frescura casual americana de los 90. Menta refrescante, manzana verde crujiente, arándanos y flores de algodón. Huele a juventud, a limpieza, a jeans y camiseta blanca. Atemporal, inofensivo y perfecto para el verano o después de ducharse." }
        "(?i)^Uomo Born In Roma( Set)?$" { $tips = "Un éxito masivo en la perfumería moderna masculina. Su secado es espectacular y versátil, jugando con un contraste de hojas de violeta, acordes minerales salados y un dulzor fresco de maderas y jengibre. Genera muchísimos cumplidos en citas o salidas informales." }
        "(?i)^Spicebomb$" { $tips = "Una verdadera 'bomba de especias'. La mezcla explosiva de pimienta, canela picante y azafrán, contrastada con cuero, tabaco y bergamota fresca. Es cálido, seductor y vibrante. La elección definitiva para destacar en invierno o en las noches más frías." }
        "(?i)^Libre$" { $tips = "La fragancia que redefinió la elegancia moderna femenina. Toma la lavanda (históricamente masculina) y la feminiza magistralmente con flor de azahar luminosa, mandarinas y un fondo cálido de vainilla. Proyecta una mujer fuerte, libre, exitosa y empoderada." }
        "(?i)^Ajwad$" { $tips = "Una bestia del rendimiento de Lattafa. Su perfil olfativo es complejo y metálico: un dulzor frutal estridente y sintético en la salida que da paso a una rosa avainillada muy densa, ámbar y cedro. Dura días en la ropa. Solo para personas que buscan llenar una habitación." }
        "(?i)^Victoria$" { $tips = "Una apuesta segura y versátil de Lattafa para el día a día. Flores silvestres dulces combinadas con un fondo reconfortante de vainilla y maderas suaves. Femenino, sutil, agradable y excelente para tener un aroma delicado sin gastar demasiado." }
        "(?i)^Ombre Nomade$" { $tips = "Opulencia, lujo y poder embotellado. Una de las fragancias más imponentes que existen. Destaca un cuero oscuro y pesado, madera de oud potente y una frambuesa intensa que le da un toque dulce y ahumado espectacular. Estela masiva, solo para vestimenta de lujo." }
        "(?i)^Odyssey Collection$" { $tips = "Línea completa de Armaf con enfoques frescos, cítricos y frutales. Representan inspiración en fragancias de diseñador altamente exitosas. Excelente relación calidad-precio." }
        "(?i)^Art of Universe$" { $tips = "Fragancia árabe de altísima calidad enfocada en la limpieza y frescura. Cítricos radiantes (mandarina/bergamota) mezclados con flores y jengibre picante. Energizante, luminoso y con una duración sorprendente para su perfil fresco. Ideal para el verano absoluto." }
        "(?i)^Yum Yum$" { $tips = "Fragancia puramente gourmand, juvenil y deliciosa. Como su nombre indica, evoca postres dulces y frutos rojos cremosos. Ideal para mujeres que disfrutan los aromas comestibles, divertidos y con mucha proyección." }
    }
    
    if ($tips) {
        # Columna 6 es Inspiracion_Ventas
        $worksheet.Cells.Item($row, 6).Value2 = $tips
    }
}

# Delete column 7 (Archivo_Foto)
$worksheet.Columns.Item(7).Delete()

$worksheet.Columns.Item(6).ColumnWidth = 80
$worksheet.Columns.Item(6).WrapText = $true

$worksheet.Rows.AutoFit() | Out-Null
$workbook.Save()
$workbook.Close()
$excel.Quit()
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
Write-Host "Inspiracion de ventas expandida y foto eliminada."
